"""
Memo Template Engine

Constructs the final assessment memo as a structured JSON object.
This structure ensures the LLM's explanation is properly framed by
the deterministic verdict and numeric ranges.

G5 FIX: Added document_checklist block per §9.3 of the brief —
"Exactly which documents to gather, and where each is obtained."
The checklist is dynamically tailored to the tenure type.
"""
from typing import Dict, Any, Optional, List
from datetime import datetime
from engine.schemas import Verdict, VerdictCategory, TenureType


# Document checklists by tenure type (§9.3 compliance)
_DOCUMENT_CHECKLISTS: Dict[str, List[Dict[str, str]]] = {
    "owned": [
        {"doc": "7/12 extract (Satbara Utara) or RTC (Record of Rights, Tenancy & Crops)", "source": "State Revenue Department / Bhoomi portal"},
        {"doc": "Mutation entry / Patta deed", "source": "Sub-Registrar / Revenue office"},
        {"doc": "Aadhaar card of all co-owners", "source": "UIDAI / local Aadhaar centre"},
        {"doc": "Encumbrance Certificate (last 30 years)", "source": "Sub-Registrar office"},
        {"doc": "Land classification certificate (confirming non-forest status)", "source": "Tehsildar / Revenue Inspector"},
        {"doc": "Survey / boundary map (e.g. FMB or Tippan sketch)", "source": "District Survey office"},
    ],
    "leased": [
        {"doc": "Registered lease deed (30-year minimum preferred)", "source": "Sub-Registrar office"},
        {"doc": "Lessor's 7/12 or title document", "source": "Revenue Department"},
        {"doc": "NOC from landowner for carbon project activities", "source": "Mutual agreement — must be notarised"},
        {"doc": "Aadhaar card of lessee and lessor", "source": "UIDAI"},
        {"doc": "Land classification certificate", "source": "Tehsildar"},
    ],
    "community": [
        {"doc": "Gram Sabha resolution authorising the project", "source": "Gram Panchayat records"},
        {"doc": "FRA (Forest Rights Act) community title, if applicable", "source": "District Collector / SDLC"},
        {"doc": "Revenue record / patta in the name of the Gram Panchayat", "source": "Revenue Department"},
        {"doc": "List of beneficiary families with signatures/Aadhaar", "source": "Self-generated, notarised"},
        {"doc": "Minutes of community meeting agreeing to 30-year commitment", "source": "Gram Sabha records"},
    ],
    "government": [
        {"doc": "Government lease / patta granted to applicant", "source": "State Forest Dept / Revenue Dept"},
        {"doc": "Government NOC for commercial carbon project activities", "source": "Issuing government department"},
        {"doc": "Land use permission / development order", "source": "District Collector"},
        {"doc": "Aadhaar of authorised signatory", "source": "UIDAI"},
    ],
    "default": [
        {"doc": "Primary land record (7/12, patta, RTC, or equivalent)", "source": "State Revenue Department"},
        {"doc": "Identity proof of landowner/applicant (Aadhaar)", "source": "UIDAI / Aadhaar centre"},
        {"doc": "Land classification certificate confirming non-forest status", "source": "Tehsildar / Revenue Inspector"},
        {"doc": "Encumbrance Certificate", "source": "Sub-Registrar office"},
        {"doc": "Survey / boundary sketch of the parcel", "source": "District Survey office"},
    ],
}


def _get_document_checklist(intake_data: Optional[Dict[str, Any]]) -> List[Dict[str, str]]:
    """
    Returns the appropriate document checklist based on land tenure type.
    """
    if not intake_data:
        return _DOCUMENT_CHECKLISTS["default"]
    tenure = str(intake_data.get("tenure_type", "")).lower()
    return _DOCUMENT_CHECKLISTS.get(tenure, _DOCUMENT_CHECKLISTS["default"])


class MemoTemplateEngine:
    """
    Constructs the final assessment memo as a structured JSON object.
    This structure ensures the LLM's explanation is properly framed by
    the deterministic verdict and numeric ranges.
    """

    @staticmethod
    def build_memo(verdict: Verdict, explanation: str, intake_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Build a complete structured memo from a Verdict object and LLM explanation.

        Args:
            verdict: The deterministic verdict from the rules engine.
            explanation: Plain-English explanation generated by the LLM.
            intake_data: Optional intake data for contextualising the document checklist.
        """
        memo: Dict[str, Any] = {
            "generated_at": datetime.utcnow().isoformat() + "Z",
            "disclaimer": verdict.disclaimer,
            "verdict": {
                "category": verdict.verdict.value,
                "confidence": verdict.confidence,
                "confidence_reason": verdict.confidence_reason,
                "is_eligible": verdict.verdict not in [
                    VerdictCategory.not_eligible_structural,
                    VerdictCategory.insufficient_information,
                ],
                "knockout_gate": verdict.knockout_gate,
            },
            "why": explanation,
        }

        if verdict.indicative_numbers:
            n = verdict.indicative_numbers
            memo["financials"] = {
                "annual_credits_range": [n.annual_credits_low, n.annual_credits_high],
                "revenue_usd_range": [n.revenue_usd_low, n.revenue_usd_high],
                "first_issuance_years": [n.first_issuance_year_min, n.first_issuance_year_max],
            }

        if verdict.flags:
            memo["risk_flags"] = verdict.flags

        if verdict.next_steps:
            memo["next_steps"] = verdict.next_steps

        if verdict.alternatives:
            memo["alternatives"] = verdict.alternatives

        if verdict.questions_to_ask_developer:
            memo["developer_questions"] = verdict.questions_to_ask_developer

        if verdict.what_we_could_not_check:
            memo["unverified_fields"] = verdict.what_we_could_not_check

        # G5 FIX: Add document checklist block (§9.3)
        memo["document_checklist"] = _get_document_checklist(intake_data)

        return memo
