import logging
from orchestrator.state import ConversationState
from orchestrator.llm_schemas import ExplainOutput
from orchestrator.llm_caller import llm_caller

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the explanation layer of a Carbon Credit Consultant Chatbot.
Your job is to explain the verdict generated by the rules engine in plain, empathetic English.

CRITICAL INSTRUCTION:
- You DO NOT decide eligibility. The verdict is already decided and provided to you.
- Your ONLY job is to explain WHY the verdict is what it is, based on the engine's reason.
- Do not promise guaranteed returns. Keep tone objective but helpful.
- If the verdict is a structural knockout, be direct but polite, and point to alternatives.
"""

async def explain_node(state: ConversationState) -> ConversationState:
    """
    Takes the deterministic verdict and uses the LLM to explain it to the user.
    """
    verdict = state.get("verdict")
    if not verdict:
        logger.error("Explain node called but no verdict in state.")
        return state
        
    prompt = (
        f"The rules engine has evaluated the user's land and produced the following verdict:\n\n"
        f"Verdict Category: {verdict.verdict.value}\n"
        f"Confidence Level: {verdict.confidence}\n"
        f"Engine Reason: {verdict.confidence_reason}\n"
        f"Flags: {verdict.flags}\n"
        f"Knockout Gate (if any): {verdict.knockout_gate}\n\n"
        f"Explain this clearly to the user."
    )
    
    try:
        explanation_output = await llm_caller.call_with_schema(
            prompt=prompt,
            schema=ExplainOutput,
            system_prompt=SYSTEM_PROMPT
        )
        
        # Append the explanation to the conversation
        state["messages"].append({"role": "assistant", "content": explanation_output.explanation})
        
        # If there's a clarifying question (e.g., Tier 2 refinement), save it
        if explanation_output.clarifying_question:
            state["current_question"] = explanation_output.clarifying_question
            state["messages"].append({"role": "assistant", "content": explanation_output.clarifying_question})
            
        # Update UI state to show the memo button
        state["ui_state"] = {"show_memo_button": True, "verdict_category": verdict.verdict.value}
        
    except Exception as e:
        logger.error(f"Explain generation failed: {e}")
        # Fallback to the raw engine reason if LLM fails
        state["messages"].append({"role": "assistant", "content": f"Verdict: {verdict.verdict.value}. Reason: {verdict.confidence_reason}"})
        state["ui_state"] = {"show_memo_button": True, "verdict_category": verdict.verdict.value}
        
    return state
