"""
RAG chunker — clause-level structural chunking with document-level summary.

Design (from technical plans):
  - Clause/paragraph-level chunking (NOT fixed-size character chunking)
  - Each chunk has a document-level summary prepended before embedding
    (fixes "document-level retrieval mismatch" in legal/regulatory corpora)
  - Metadata: doc_title, version, effective_date, jurisdiction, page_num, chunk_index
"""

from __future__ import annotations
import os
from typing import List
from dataclasses import dataclass, field

try:
    import pdfplumber
    HAS_PDF = True
except ImportError:
    HAS_PDF = False


@dataclass
class DocumentChunk:
    document_id: str
    chunk_index: int
    content: str              # raw chunk text
    doc_summary: str          # document-level summary prepended for embedding
    embed_text: str           # content to embed = doc_summary + "\n\n" + content
    metadata: dict = field(default_factory=dict)


def _extract_text_from_pdf(file_path: str) -> tuple[str, list[str]]:
    """Returns (full_text, list_of_page_texts)."""
    if not HAS_PDF:
        raise ImportError("pdfplumber not installed. Run: pip install pdfplumber")

    pages = []
    with pdfplumber.open(file_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text() or ""
            pages.append(text)
    return "\n\n".join(pages), pages


def _extract_text_from_txt(file_path: str) -> tuple[str, list[str]]:
    with open(file_path, "r", encoding="utf-8", errors="replace") as f:
        text = f.read()
    return text, [text]


def _extract_text(file_path: str) -> tuple[str, list[str]]:
    ext = os.path.splitext(file_path)[1].lower()
    if ext == ".pdf":
        return _extract_text_from_pdf(file_path)
    elif ext in (".txt", ".md"):
        return _extract_text_from_txt(file_path)
    else:
        return _extract_text_from_txt(file_path)


def _split_into_clauses(text: str, max_chars: int = 1200) -> List[str]:
    """
    Split text into clause-level chunks by paragraph breaks.
    If a paragraph is longer than max_chars, split further at sentence boundaries.
    """
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]
    chunks = []
    for para in paragraphs:
        if len(para) <= max_chars:
            chunks.append(para)
        else:
            # Split long paragraph at sentence endings
            sentences = para.replace(". ", ".\n").split("\n")
            current = ""
            for sent in sentences:
                if len(current) + len(sent) + 1 <= max_chars:
                    current = (current + " " + sent).strip()
                else:
                    if current:
                        chunks.append(current)
                    current = sent
            if current:
                chunks.append(current)
    return chunks


def _generate_doc_summary(title: str, first_chunk: str) -> str:
    """
    Simple document-level summary prepended to every chunk before embedding.
    In Phase 2, this can be generated by the LLM for richer summaries.
    """
    excerpt = first_chunk[:200].replace("\n", " ")
    return f"Document: {title}. Summary excerpt: {excerpt}..."


def chunk_document(file_path: str, document_id: str, title: str, max_chars: int = 1200) -> List[DocumentChunk]:
    """
    Main entry point — chunk a document file into DocumentChunk objects.
    """
    full_text, _ = _extract_text(file_path)
    raw_chunks = _split_into_clauses(full_text, max_chars=max_chars)

    if not raw_chunks:
        return []

    doc_summary = _generate_doc_summary(title, raw_chunks[0])

    result = []
    for idx, content in enumerate(raw_chunks):
        if not content.strip():
            continue
        embed_text = f"{doc_summary}\n\n---\n\n{content}"
        chunk = DocumentChunk(
            document_id=document_id,
            chunk_index=idx,
            content=content,
            doc_summary=doc_summary,
            embed_text=embed_text,
            metadata={"title": title, "chunk_index": idx},
        )
        result.append(chunk)

    return result
